Repository Siriuscoder/3dlite, pull requests merged in 2018-10, with the labels that each got.

#60 Поддержка off-screen MSAA
  lite3d/include/lite3d/lite3d_framebuffer.h
  lite3d/include/lite3d/lite3d_glext.h
  lite3d/include/lite3d/lite3d_misc.h
  lite3d/include/lite3d/lite3d_texture_unit.h
  lite3d/src/lite3d_framebuffer.c
  lite3d/src/lite3d_glext.c
  lite3d/src/lite3d_misc.c
  lite3d/src/lite3d_pack.c
  lite3d/src/lite3d_render.c
  lite3d/src/lite3d_shader.c
  lite3d/src/lite3d_shader_program.c
  lite3d/src/lite3d_tbo.c
  lite3d/src/lite3d_texture_unit.c
  lite3d/src/lite3d_vao.c
  lite3d/src/lite3d_vbo.c
  lite3dpp/include/lite3dpp/lite3dpp_observer.h
  lite3dpp/include/lite3dpp/lite3dpp_texture.h
  lite3dpp/include/lite3dpp/lite3dpp_texture_render_target.h
  lite3dpp/src/lite3dpp_render_target.cpp
  lite3dpp/src/lite3dpp_texture.cpp
  lite3dpp/src/lite3dpp_texture_render_target.cpp
  media/samples/textures/json/multisample4Depth.json
  media/samples/textures/json/multisample8Depth.json
  media/sponza/config/config_sponza.json
  media/sponza/shaders/sources/postprocess.ps
  media/sponza/shaders/sources/postprocess.vs
  media/sponza/targets/depth.json
  media/sponza/targets/postrender.json
  media/sponza/targets/render.json
  samples/sample_rtt/lite3d_sample_rtt.c
Labels: enhancement

#59 Issue42
  CMake/FindDevIL.cmake
  lite3d/include/lite3d/GL/glew.h
  lite3d/include/lite3d/lite3d_main.h
  lite3d/include/lite3d/lite3d_video.h
  lite3d/src/glew/glew.c
  lite3d/src/lite3d_glext.c
  lite3d/src/lite3d_main.c
  lite3d/src/lite3d_material.c
  lite3d/src/lite3d_vbo.c
  lite3d/src/lite3d_video.c
  lite3dpp/src/lite3dpp_main.cpp
Labels: bug, enhancement

#63 Исправление ошибок вызванных рефакторингом
  lite3d/src/lite3d_tbo.c
  lite3dpp/src/lite3dpp_texture.cpp
Labels: bug

#64 LUMINANCE texture format replaced by RED
  lite3d/src/lite3d_texture_unit.c
Labels: bug
